# This workflow will do a clean install of node dependencies, build the source code and deploy it using the deploy shell file

name: Vue Deployment

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Installing...
        run: npm ci

      - name: Set up credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          name: 'jh8oh'
          email: 'ohjiho.ca@gmail.com'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Deploying...
        run: sh deploy.sh

