# This workflow will do a clean install of node dependencies, build the source code and deploy it using the deploy shell file

name: Vue Deployment

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Installing...
        run: npm ci

      - name: Linting...
        run: npm run lint

      - name: Building...
        run: npm run build

      - name: Deploying...
        run: |
          cd dist
          git config user.email "ohjiho.ca@gmail.com"
          git config user.name "jh8oh"
          git init
          git add -A
          git commit -m 'Deployment'
          git push -f git@github.com:jh8oh/jh8oh.github.io.git master


